mod 'stahnma/epel'
mod 'ghoneycutt/dnsclient'
mod 'garethr/docker'
mod 'puppetlabs/apache'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/firewall'
mod 'puppetlabs/inifile'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/concat'
mod 'puppetlabs/java'                                                                                                                   
mod 'rtyler/jenkins'
mod 'puppetlabs/apt'
mod 'darin/zypprepo'
mod 'ispavailability/file_concat'
mod 'puppetlabs/vcsrepo'
mod 'theforeman/git'
mod 'spuder/gitlab'
#mod 'jorhett/mcollective'
mod 'zack/r10k'


# This stuff is needed for zack/r10k
mod 'puppetlabs/ruby'

#Hacked mcollective module
mod 'mcollective',
  :git => 'https://github.com/b1-systems/puppet-mcollective.git',
  :branch => 'master'

